import time


def fibb(a,b,result=0):
    '''Fibonacci sequence'''
    while b < 4000000: # 4000000 - number from task 
        if b % 2 == 0:
            result += b
        a, b = b, a + b # 1, 2 = 2, 3
    return result


if __name__ == "__main__":
    '''
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
    '''
    timer_start = time.time()

    print(f'\nResult = {fibb(1,2)}')
    
    timer_stop = time.time()
    print(f'\nSpend time: {round(timer_stop-timer_start, 5)} seconds')